heat_template_version: 2013-05-23

parameters:
  private_network_param:
    type: string
  public_network_param:
    type: string
  global_security_group_param:
    type: string
  prod_security_group_param:
    type: string
  test_floating_ip_param:
    type: string
  prod_tmp_floating_ip_param:
    type: string
  prod_floating_ip_param:
    type: string
  ssh_key_param:
    type: string

# declaration of template resources
resources:
  # Creation of a private network to host services
  private_network:
    type: OS::Neutron::Net
    properties:
      name: { get_param: private_network_param }

  # Creation of a subnet network on the private network
  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_network }
      ip_version: 4
      cidr: "192.168.0.0/24"
      enable_dhcp: True
      allocation_pools:
        - start: "192.168.0.10"
          end: "192.168.0.250"

  # Creation of a bridge router between the public and private network
  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: { network: {get_param: public_network_param} }    # public network already created

  # Creation of an interface between the router and the private network
  router-interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet: { get_resource: private_subnet }

  # Key-pair
  key-pair:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: ssh_key_param }
      save_private_key: True

  # Security groups
  global_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: { get_param: global_security_group_param }
      rules:
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 22
          port_range_max: 22
  
  prod_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: { get_param: prod_security_group_param }
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 80
          port_range_max: 80
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 443
          port_range_max: 443

  # Floating ips
  test_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_ip_address: { get_param: test_floating_ip_param }
      floating_network: { get_param: public_network_param }

  prod_tmp_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_ip_address: { get_param: prod_tmp_floating_ip_param }
      floating_network: { get_param: public_network_param }

  prod_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_ip_address: { get_param: prod_floating_ip_param }
      floating_network: { get_param: public_network_param }

outputs:
  ssh_key:
    value:
      get_attr: [key-pair, private_key]
  private_network:
    value:
      get_attr: [private_network, name]
