heat_template_version: 2013-05-23
description: Template to deploy a test stack

# declaration of template resources
resources:
  # Creation of a private network to host services
  private_network:
    type: OS::Neutron::Net
    properties:
      name: private

  # Creation of a subnet network on the private network
  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_network }
      ip_version: 4
      cidr: "192.168.0.0/24"
      enable_dhcp: True
      allocation_pools:
        - start: "192.168.0.10"
          end: "192.168.0.250"

  # Creation of a bridge router between the public and private network
  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: { network: public }    # public network already created

  # Creation of an interface between the router and the private network
  router-interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet: { get_resource: private_subnet }

  # Key-pair
  key-pair:
    type: OS::Nova::KeyPair
    properties:
      name: ssh_orchestration_key
      save_private_key: True

  # Security groups
  global_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 22
          port_range_max: 22
  
  prod_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 80
          port_range_max: 80
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 443
          port_range_max: 443

outputs:
  ssh_key:
    value:
      get_attr: [key-pair, private_key]
