- hosts: jenkins
  vars:
    jenkins_hostname: localhost
    jenkins_http_port: 8080
    jenkins_plugins: ["github", "github-issues", "github-branch-source", "workflow-aggregator"]
  tasks:
    - name: install pip3
      apt:
        name: python3-pip
        state: latest
    - name: install docker compose
      pip:
        name: docker-compose
        executable: pip3
      become: True
    - name: install requests
      pip:
        name: requests
        executable: pip3
      become: True
    - name: install slack client
      pip:
        name: slackclient
        executable: pip3
      become: True
    - name: jenkins_jobs_create
      shell: rm -rf /var/lib/jenkins/jobs/github_multibranch_pipeline; cp -p -r ~/cloud_native_app/deployment/jenkins/jobs/github_multibranch_pipeline /var/lib/jenkins/jobs/github_multibranch_pipeline; service jenkins restart
      become: true
  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
      become: true
