- hosts: openstack
  tasks:
    - git:
        repo: 'https://git.openstack.org/openstack/openstack-ansible'
        dest: /opt/openstack-ansible
    - shell: /opt/openstack-ansible/bootstrap-ansible.sh
      become: true
    - shell: /opt/openstack-ansible/bootstrap-aio.sh
      become: true
    - shell: openstack-ansible /opt/openstack-ansible/playbooks/setup-hosts.yml
      become: true
    - shell: openstack-ansible /opt/openstack-ansible/playbooks/setup-infrastructure.yml
      become: true
    - shell: openstack-ansible /opt/openstack-ansible/playbooks/setup-openstack.yml
      become: true

