pipeline {
	agent any
		stages {
			stage('Build') {
				steps {
					echo 'Building..'
					sh './scripts/build.py'
					sh 'printenv'
				}
			}
			stage('Test') {
				steps {
					echo 'Testing..'
				}
			}
			stage('Deploy') {
				steps {
					echo 'Deploying....'
				}
			}
		}
}
