pipeline {
	agent any
	stages {
		stage('Build') {
			when { branch 'dev' }
			steps { sh 'docker-compose build' }
		}
		stage('Test') {
			when { branch 'dev' }
			steps {
                sh 'docker-compose up -d'
                sh './deployment/jenkins/scripts/test.py'
                sh 'docker-compose stop'
            }
		}
		stage('Deploy') {
			when { branch 'master' }
			steps { sh './deployment/jenkins/scripts/deploy.py' }
		}
	}
}
